---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-qwe1/docker-debian:10-molecule}"
    privileged: true
    pre_build_image: true
    command: ""
    pull: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - grub
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      grub:
        GRUB_CMDLINE_LINUX_DEFAULT: "quiet"
scenario:
  name: default
